version: '3.3'

services:
  train:
    image: tensorflow/tensorflow:latest
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: make DEV 

  tensorboard:
    build:
      context : .
    command: tensorboard --logdir logs/ --host 0.0.0.0 --port=6006
    ports:
      - 6006:6006

